stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -t private.parrot.run/website:latest .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker push private.parrot.run/website:latest